### PR TITLE
feat(ratatui): add Ratatui support

### PR DESCRIPTION
**Pull request by joshka**
Ratatui is an actively maintained fork of tui-rs. See https://ratatui.rs

---

Note: I think it's probably a good idea to keep tui-rs support and add ratatui here rather than deprecating tui-rs.
The implementation is mostly copied from the Tui feature, changing the necessary bits (`Spans` -> `Line`, etc.)

### CODE REVIEW

**Comment by joshka** [comment]
We are also considering adding some sort of functionality like this directly in Ratatui in https://github.com/ratatui-org/ratatui/issues/493

**Comment by 7sDream** [comment]
Thanks!

I’m actually aware that the community has taken over tui and forked it into ratatui, and I indeed have thoughts of supporting it. However, as my main project recently does not heavily use TUI and terminal styles, I have postponed it.

I will take a close look at this PR either tonight or this weekend. Thank you again for your contribution.

**Comment by joshka** [comment]
No problem on the timing. To make it easy to review, you'll pretty much find that this PR copies the Tui module exactly and just renames the appropriate things (Tui -> Ratatui, and Spans -> Line). To save yourself some time, consider just doing a `diff -u src/generator/tui/mod.rs src/generator/ratatui/mod.rs` etc.

We introduced string parsing (`impl FromStr`) a while back for `Color` and `Modifier`, so it might be worth looking at those to see if we can support the same values.

Once this is merged, I think this crate would be good fit to add to the recently added https://ratatui.rs/showcase/third-party-widgets/ page.

**Comment by 7sDream** [comment]
There are no problems with the code, but there are two things that need to be discussed:

1. As per your statement, the support code for ratatui essentially replicates the tui part. Considering that the original tui-rs project is no longer under active maintenance, is it necessary to continue supporting it? My inclination would be to shift support from tui to ratatui. If there are users who still require tui-rs support, they could remain on version 0.3 (we can include this information in the README).

2. I think it is very reasonable to use the `FromStr` implementation in ratatui when parsing style tag. (I did not find the `FromStr` implementation of `Modifier`, so I will skip this for now.) For `Color`, there seems to be an issue. When dealing with RGB colors, ratatui’s implementation necessitates the use of `#` at the start of the hex color string, but current lexical parser of tui-markup does not permit this character. Is it feasible for ratatui to make the `#` optional? Alternatively, I could contemplate permitting the `#` during parsing.

**Comment by joshka** [comment]
1. I probably should have looked at the dependents. It's just a few apps and you own most of them, so dropping tui would be the right idea. https://github.com/7sDream/tui-markup/network/dependents
2. I left this alone mainly because of the differences between our implementation and yours. Maybe cut a quick issue in the ratatui repo about whether bare hex strings makes sense. I'm not sure off the top my head - other maintainers might have a perspective on it. This is something that can happen later too.

**Comment by 7sDream** [comment]
OK, then I think you can update the PR to replace tui-rs with ratatui, and keep the color/modifier convert section for now, I can change to use FromStr after merging.

**Comment by joshka** [comment]
Removed TUI-rs in the latest change.

**Comment by 7sDream** [comment]
Sorry for the late, Thank you!

**Comment by joshka** [comment]
> Sorry for the late, Thank you!

No problem.

**Pull request merged**
